import { Card } from "@/components/ui/Card";
import { SourceBadge } from "./SourceBadge";
import { AIExplanation, DataSourceInfo } from "@/lib/types";

interface AIExplanationCardProps {
  explanation: AIExplanation;
  source: DataSourceInfo;
}

// Only renders when the backend has an LLM configured and successfully
// generated a narrative - otherwise ai_explanation is simply absent from the
// report and this component is never mounted. No "coming soon" placeholder.
export function AIExplanationCard({ explanation, source }: AIExplanationCardProps) {
  return (
    <Card className="p-6 ring-1 ring-purple-400/20">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-lg font-medium">AI Summary</h2>
        <SourceBadge {...source} />
      </div>
      <p className="mt-3 text-sm">{explanation.narrative}</p>

      {explanation.additional_notes.length > 0 && (
        <ul className="mt-4 space-y-1.5 text-sm text-muted">
          {explanation.additional_notes.map((note, i) => (
            <li key={i} className="flex gap-2">
              <span>-</span>
              <span>{note}</span>
            </li>
          ))}
        </ul>
      )}

      <p className="mt-4 text-xs text-muted">
        Generated by AI from the data above - not an independent source.
      </p>
    </Card>
  );
}
